/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-10-10 07:11:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qa.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/cvcbank/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mngbot/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1524211722455L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link href=\"/css/bootstrap.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/bootstrap.js\"></script>\r\n");
      out.write("<link href=\"/css/summernote.css\" rel=\"stylesheet\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"/js/summernote.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div class=\"pop_wrap\" style=\"width:780px;\">\r\n");
      out.write("\t<form name=\"editForm\" method=\"post\" enctype=\"multipart/form-data\" onsubmit=\"return false;\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"seq\" v-model=\"seq\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"pid\" v-model=\"view.pid\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"regId\" v-model=\"view.regId\" />\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"fileList\" v-model=\"view.fileList\" />\r\n");
      out.write("\t<div class=\"pop_tit\">\r\n");
      out.write("\t\t<p>{{ mod ? '게시글 조회' : '새글쓰기' }}</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"pop_cont\">\r\n");
      out.write("\t\t<div class=\"g_table02\">\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<caption>제목, 내용, 첨부파일 등을 입력하는 표 입니다.</caption>\r\n");
      out.write("\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t<col style=\"width:120px;\">\r\n");
      out.write("\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>제목</th>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"((mod && idChk) || !mod) && prjVo.projectStatCd != 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" class=\"full\" name=\"subject\" v-model=\"view.subject\" placeholder=\"최소 5글자 이상\">\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"mod && !idChk && prjVo.projectStatCd != 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t{{ view.subject }}\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"prjVo.projectStatCd == 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t{{ view.subject }}\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"!mod\">\r\n");
      out.write("\t\t\t\t\t\t\t{{user.loginUserNm}}({{user.loginUserGroupNm}})\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"mod\">\r\n");
      out.write("\t\t\t\t\t\t\t{{view.userNm}}({{view.userGroupNm}})\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>내용</th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"notice_txt\" v-if=\"((mod && idChk) || !mod) && prjVo.projectStatCd != 'C304'\">\r\n");
      out.write("<!-- \t\t\t\t\t\t\t<textarea name=\"content\" v-model=\"view.content\" class=\"full\"></textarea> -->\r\n");
      out.write("\t\t\t\t\t\t\t<textarea id=\"summernote\" name=\"content\" class=\"full\"></textarea>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"notice_txt\" v-if=\"mod && !idChk && prjVo.projectStatCd != 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"txt\" v-html=\"view.content\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"prjVo.projectStatCd == 'C304'\" class=\"notice_txt\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"txt\" v-html=\"view.content\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>첨부파일 </th>\r\n");
      out.write("\t\t\t\t\t\t<td class=\"file\" v-if=\"((mod && idChk) || !mod ) && prjVo.projectStatCd != 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"file\" class=\"ir\" id=\"upLoadFile\" name=\"uploadFile\" @change=\"btnFileUpload\" :disabled=\"mod && !idChk\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"upLoadFile\" class=\"sch_file\" >파일찾기</label>\r\n");
      out.write("\t\t\t\t\t\t\t<p class=\"file_txt\">최대 10MB 까지 첨부 가능합니다.</p>\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"file_list\" v-show=\"view.fileList.length>0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"full\" v-for=\"(fn,index) in view.fileList\"><a @click=\"getFileDown(index)\">{{fn.orgFileNm}}</a><button class=\"del\"  @click=\"btnFileDelete(index)\"> </button></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"mod && !idChk && orgFileNm=='' && prjVo.projectStatCd != 'C304' \">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"file_list\" v-show=\"view.fileList.length>0\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"full\" v-for=\"(fn,index) in view.fileList\"><a @click=\"getFileDown(index)\">{{fn.orgFileNm}}</a></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td v-if=\"prjVo.projectStatCd == 'C304'\">\r\n");
      out.write("\t\t\t\t\t\t\t<ul class=\"file_list\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<li class=\"full\" v-for=\"(fn,index) in view.fileList\"><a style=\"padding-left: 5px;\" @click=\"getFileDown(index)\">{{fn.orgFileNm}}</a><button class=\"del\"  @click=\"btnFileDelete(index)\"> </button></li>\r\n");
      out.write("\t\t\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 코멘트 영역 -->\r\n");
      out.write("\t\t<div v-if=\"user.userId == 'U0001' && mod\">\r\n");
      out.write("\t\t\t<p class=\"cate_tit\">코멘트</p>\r\n");
      out.write("\t\t\t<div class=\"search_area\"> \r\n");
      out.write("\t\t\t\t<textarea class=\"issue_comment\" id=\"boardComment\" name=\"comment\"></textarea>\r\n");
      out.write("\t\t\t\t<button v-if=\"buttonFlag==false\" class=\"btn_default\" @click=\"regComment\">등록</button>\r\n");
      out.write("\t\t\t\t<button v-else class=\"btn_default\" @click=\"modComment\">수정</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"g_table\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width: 20%;\">\r\n");
      out.write("\t\t\t\t\t\t<col>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width: 20%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width: 10%;\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>등록일시</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>코멘트</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>작성자</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>관리</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr v-if=\"pagingCommentList.length==0\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"4\">등록된 코멘트가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr v-for=\"list in pagingCommentList\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.regDtm | dateTimeFormat }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"l_align\"><span v-html=\"list.comment\"></span></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.regNm }}({{ list.regGroupNm }})</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td class=\"tb_fixed_btns\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"smbtn_proc\" @click=\"commentEdit(list.comment, list.commentSeq)\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<paginator ref=\"paginatorComment\" :go-fn=\"getPagingCommentList\" init-rows=\"5\"></paginator>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t<button v-if=\"mod && idChk && prjVo.projectStatCd != 'C304'\" class=\"btn_proc\" @click=\"btnModify\">수정</button>\r\n");
      out.write("\t\t<button v-if=\"mod && idChk && prjVo.projectStatCd != 'C304'\" class=\"btn_cancel\" @click=\"btnDelete\">삭제</button>\r\n");
      out.write("\t\t<button class=\"btn_proc\" v-if=\"!mod && prjVo.projectStatCd != 'C304'\" @click=\"btnSave\">등록</button>\r\n");
      out.write("\t\t<button class=\"btn_cancel\" onclick=\"hidePopupLayer(); return false\">닫기</button>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar boardView = new Vue({\r\n");
      out.write("\t\tel: \".pop_wrap\"\r\n");
      out.write("\t\t, data: {\r\n");
      out.write("\t\t\tview: {\r\n");
      out.write("\t\t\t\tsubject: \"\"\r\n");
      out.write("\t\t\t\t, content: \"\"\r\n");
      out.write("\t\t\t\t, fileList:[]\r\n");
      out.write("\t\t\t\t, pid : \"");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, seq: \"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\"\r\n");
      out.write("\t\t\t, mod: false\r\n");
      out.write("\t\t\t, idChk: false\r\n");
      out.write("\t\t\t, fileNm: ''\r\n");
      out.write("\t\t\t, filePath: ''\r\n");
      out.write("\t\t\t, orgFileNm: ''\r\n");
      out.write("\t\t\t, uploadFileNm: ''\r\n");
      out.write("\t\t\t, user: {\r\n");
      out.write("\t\t\t\tuserId: '");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t\t, loginUserNm: '");
      if (_jspx_meth_c_005fout_005f3(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t\t, loginUserGroupNm: '");
      if (_jspx_meth_c_005fout_005f4(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, prjVo:{\r\n");
      out.write("\t\t\t\tprojectStatCd: '");
      if (_jspx_meth_c_005fout_005f5(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, buttonFlag: false\r\n");
      out.write("\t\t\t, procChk: false\r\n");
      out.write("\t\t\t, pagingCommentList: []\r\n");
      out.write("\t\t\t, commentSeq: ''\r\n");
      out.write("\t\t\t, commentList:[]\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, updated: function(){\r\n");
      out.write("\t\t\tsetPopup(2);\r\n");
      out.write("\t\t\tthis.setContents();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, mounted: function(){\r\n");
      out.write("\t\t\tvar paramSeq = \"");
      if (_jspx_meth_c_005fout_005f6(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\t\tthis.$nextTick(function(){\r\n");
      out.write("\t\t\t\tif(!isEmpty(paramSeq)){\r\n");
      out.write("\t\t\t\t\tthis.getView(paramSeq);\r\n");
      out.write("\t\t\t\t\tboardView.mod = true;\r\n");
      out.write("\t\t\t\t\t//넥스트랩 계정일때 코맨트 리스트 조회\r\n");
      out.write("\t\t\t\t\tif(boardView.user.userId == 'U0001'){\r\n");
      out.write("\t\t\t\t\t\tthis.getBoardCommentList(paramSeq);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tthis.setContents();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tsetPopup(2);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, methods: {\r\n");
      out.write("\t\t\tsetContents: function() {\r\n");
      out.write("\t\t\t\t$('#summernote').summernote({\r\n");
      out.write("\t\t\t\t\theight: 200\r\n");
      out.write("\t\t\t\t\t, width: 300\r\n");
      out.write("\t\t\t\t\t, maxwidth: 300\r\n");
      out.write("\t\t\t\t\t, disableResizeEditor: true\r\n");
      out.write("\t\t\t\t\t, toolbar: [\r\n");
      out.write("\t\t\t\t\t\t['style', ['style', 'fontsize', 'color']],\r\n");
      out.write("\t\t\t\t\t\t['fontsize', ['bold', 'italic', 'underline', 'strikethrough']],\r\n");
      out.write("\t\t\t\t\t\t['para', ['paragraph', 'height', 'hr']],\r\n");
      out.write("\t\t\t\t\t\t['picture', ['table', 'picture', 'link']]\r\n");
      out.write("\t\t\t\t\t]\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tif (!($('#summernote').summernote('isEmpty'))) {\r\n");
      out.write("\t\t\t\t\t$('#summernote').summernote('code', $('#summernote').summernote('code'));\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t$('#summernote').summernote('code', boardView.view.content.split('\\n').join('<br>'));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, getView: function(paramSeq){\r\n");
      out.write("\t\t\t\t$.get(\"/qa/board/getBoardView?seq=\" + paramSeq,function(data){\r\n");
      out.write("\t\t\t\t\tboardView.view = data.view;\r\n");
      out.write("\t\t\t\t\tboardView.view.pid = \"");
      if (_jspx_meth_c_005fout_005f7(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\t\t\t\tboardView.view.fileList = data.fileList;\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t// 로그인 ID 와 게시글 등록ID 일치여부 확인\r\n");
      out.write("\t\t\t\t\tif (boardView.user.userId == data.view.regId){\r\n");
      out.write("\t\t\t\t\t\tboardView.idChk = true;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t//줄바꿈 적용\r\n");
      out.write("\t\t\t\t\tboardView.view.content = data.view.content.replace(/(?:\\n)/g, '<br>');\r\n");
      out.write("\t\t\t\t\tboardView.view.content.split('\\n').join('<br>');\r\n");
      out.write(" \t\t\t\t\t\r\n");
      out.write(" \t\t\t\t\tif (boardView.mod && boardView.idChk && boardView.prjVo.projectStatCd != 'C304') {\r\n");
      out.write("\t\t\t\t\t\t//줄바꿈 미적용\r\n");
      out.write("\t\t\t\t\t\tboardView.view.content = data.view.content.replace(/(?:<br>)/g, '\\n');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, btnFileUpload: function(){\r\n");
      out.write("\t\t\t\tfileUpload($(\"#upLoadFile\"), {saveFilePath: \"qa/board\"}, function(data){\r\n");
      out.write("\t\t\t\t\tvar fileData = {\r\n");
      out.write("\t\t\t\t\t\t\tfileNm: data.saveFileNm\r\n");
      out.write("\t\t\t\t\t\t\t, filePath: data.saveFilePath\r\n");
      out.write("\t\t\t\t\t\t\t, orgFileNm: data.realFileNm\r\n");
      out.write("\t\t\t\t\t\t\t, fileUrl: \"/file/download?savePath=\" + data.saveFilePath + \"&saveName=\" + data.saveFileNm + \"&realName=\" + data.realFileNm\r\n");
      out.write("\t\t\t\t\t\t\t, uploadFileNm: '' \r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tvar chNm = null;\r\n");
      out.write("\t\t\t\t\tif (fileData.orgFileNm.length > 25){\r\n");
      out.write("\t\t\t\t\t\tchNm = fileData.orgFileNm.substring(0,25);\r\n");
      out.write("\t\t\t\t\t\tfileData.uploadFileNm = chNm + \".....  \";\r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\tchNm = fileData.orgFileNm;\r\n");
      out.write("\t\t\t\t\t\tfileData.uploadFileNm = chNm + \"  \";\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\tvar fChk = boardView.view.fileList.some(function(t) {\r\n");
      out.write("\t\t\t\t\t\treturn t.orgFileNm == data.realFileNm;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t\tif(!fChk){\r\n");
      out.write("\t\t\t\t\t\tboardView.view.fileList.push(fileData);\r\n");
      out.write("\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\talert(\"이미 추가된 파일입니다.\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, getFileDown: function(index) {\r\n");
      out.write("\t\t\t\tvar i = index;\r\n");
      out.write("\t\t\t\tfileDown(boardView.view.fileList[i].filePath, boardView.view.fileList[i].fileNm, boardView.view.fileList[i].orgFileNm);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, btnFileDelete: function(index){\r\n");
      out.write("\t\t\t\tif (confirm(\"파일을 삭제 하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\tboardView.view.fileList.splice(index, 1);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, btnSave: function(){\r\n");
      out.write("\t\t\t\tvar param = boardView.view;\r\n");
      out.write("\t\t\t\tif (boardView.view.subject.length < 5){\r\n");
      out.write("\t\t\t\t\talert(\"제목을 최소 5글자 이상 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tboardView.view.content = $('#summernote').summernote('code');\r\n");
      out.write("\t\t\t\tif (boardView.view.content.length < 1){\r\n");
      out.write("\t\t\t\t\talert(\"내용을 작성해주세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tvar cmsg = \"등록하시겠습니까?\";\r\n");
      out.write("\t\t\t\tif (confirm(cmsg)){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype: \"post\"\r\n");
      out.write("\t\t\t\t\t\t, url: \"/qa/board/regBoardPrc\"\r\n");
      out.write("\t\t\t\t\t\t, contentType: \"application/json\"\r\n");
      out.write("\t\t\t\t\t\t, data : JSON.stringify(param)\r\n");
      out.write("\t\t\t\t\t\t, success: function(data){\r\n");
      out.write("\t\t\t\t\t\t\tif (data.save){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"저장되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\tparent.boardList.getBoardList(boardView.view.pid);\r\n");
      out.write("\t\t\t\t\t\t\t\thidePopupLayer();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t, error: function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\t\talert($(xhr.responseText).text());\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, btnModify: function(){\r\n");
      out.write("\t\t\t\tboardView.view.seq = \"");
      if (_jspx_meth_c_005fout_005f8(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\t\t\tvar param = boardView.view;\r\n");
      out.write("\t\t\t\tif (boardView.view.subject.length < 5){\r\n");
      out.write("\t\t\t\t\talert(\"제목을 최소 5글자 이상 입력해주세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tboardView.view.content = $('#summernote').summernote('code');\r\n");
      out.write("\t\t\t\tif (boardView.view.content.length < 1){\r\n");
      out.write("\t\t\t\t\talert(\"내용을 작성해주세요.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar cmsg = \"수정하시겠습니까?\";\r\n");
      out.write("\t\t\t\tif (confirm(cmsg)){\r\n");
      out.write("\t\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\t\ttype: \"post\"\r\n");
      out.write("\t\t\t\t\t\t, url: \"/qa/board/modBoardPrc\"\r\n");
      out.write("\t\t\t\t\t\t, contentType: \"application/json\"\r\n");
      out.write("\t\t\t\t\t\t, data : JSON.stringify(param)\r\n");
      out.write("\t\t\t\t\t\t, success: function(data){\r\n");
      out.write("\t\t\t\t\t\t\tif (data.save){\r\n");
      out.write("\t\t\t\t\t\t\t\talert(\"수정되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t\tparent.boardList.getBoardList(boardView.view.pid);\r\n");
      out.write("\t\t\t\t\t\t\t\thidePopupLayer();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t, error: function(xhr, status, error){\r\n");
      out.write("\t\t\t\t\t\t\talert($(xhr.responseText).text());\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, btnDelete: function(){\r\n");
      out.write("\t\t\t\tvar cmsg = \"게시글을 삭제하시겠습니까?\";\r\n");
      out.write("\t\t\t\tif (confirm(cmsg)){\r\n");
      out.write("\t\t\t\t\t$.post('/qa/board/delBoardPrc', {seq:boardView.seq}, function(data){\r\n");
      out.write("\t\t\t\t\t\tif (data.del){\r\n");
      out.write("\t\t\t\t\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\t\tparent.boardList.getBoardList(boardView.view.pid);\r\n");
      out.write("\t\t\t\t\t\t\thidePopupLayer();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, getBoardCommentList: function(paramSeq){\r\n");
      out.write("\t\t\t\t$.get(\"/qa/board/getBoardCommentList?seq=\" + paramSeq, function(data){\r\n");
      out.write("\t\t\t\t\tboardView.commentList = data.commentList;\r\n");
      out.write("\t\t\t\t \tboardView.getPagingCommentList();\r\n");
      out.write("\t\t\t\t\tboardView.goPageComment(1);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, getPagingCommentList: function(){\r\n");
      out.write("\t\t\t\tvar tempList = [];\r\n");
      out.write("\t\t\t\ttempList = this.$refs.paginatorComment.pagingList(boardView.commentList);\r\n");
      out.write("\t\t\t\ttempList.forEach(function(o,i){\r\n");
      out.write("\t\t\t\t\ttempList[i].comment = o.comment.replace(/(?:\\n)/g, '<br>');\r\n");
      out.write("\t\t\t\t\ttempList[i].comment.split('\\n').join('<br>');\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tthis.pagingCommentList = tempList;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, goPageComment: function(page) {\r\n");
      out.write("\t\t\t\tthis.$refs.paginatorComment.goPage(page);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, regComment: function(){\t\r\n");
      out.write("\t\t\t\tvar param={\r\n");
      out.write("\t\t\t\t\tseq : boardView.seq\r\n");
      out.write("\t\t\t\t\t, comment: $(\"#boardComment\").val()\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(param.seq == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"게시글 정보를 찾을 수 없습니다.\")\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(param.comment == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"코멘트를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(boardView.procChk) return;\r\n");
      out.write("\t\t\t\tboardView.procChk = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.post('/qa/board/regBoardCommentPrc', param, function(data){\r\n");
      out.write("\t\t\t\t\tif (data.save) {\r\n");
      out.write("\t\t\t\t\t\tboardView.commentList = data.commentList;\r\n");
      out.write("\t\t\t\t\t\tboardView.getPagingCommentList();\r\n");
      out.write("\t\t\t\t\t\tboardView.goPageComment(1);\r\n");
      out.write("\t\t\t\t\t} else if (data.message) {\r\n");
      out.write("\t\t\t\t\t\talert(data.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tboardView.procChk = false;\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").val('');\r\n");
      out.write("\t\t\t\t}); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, modComment: function(){\r\n");
      out.write("\t\t\t\tvar param ={\r\n");
      out.write("\t\t\t\t\tseq: boardView.seq\r\n");
      out.write("\t\t\t\t\t, comment: $(\"#boardComment\").val()\r\n");
      out.write("\t\t\t\t\t, commentSeq: boardView.commentSeq\r\n");
      out.write("\t\t\t\t};\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(param.seq == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"게시글 정보를 찾을 수 없습니다.\")\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(param.comment == \"\"){\r\n");
      out.write("\t\t\t\t\talert(\"코멘트를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(boardView.procChk) return;\r\n");
      out.write("\t\t\t\tboardView.procChk = true;\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.post('/qa/board/modBoardCommentPrc', param, function(data){\r\n");
      out.write("\t\t\t\t\tif(data.save){\r\n");
      out.write("\t\t\t\t\t\tboardView.commentList = data.commentList;\r\n");
      out.write("\t\t\t\t\t\tboardView.getPagingCommentList();\r\n");
      out.write("\t\t\t\t\t} else if(data.message){\r\n");
      out.write("\t\t\t\t\t\talert(data.message);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tboardView.procChk = false;\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").val('');\r\n");
      out.write("\t\t\t\t\tboardView.commentSeq = '';\r\n");
      out.write("\t\t\t\t\tboardView.buttonFlag = false;\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, commentEdit: function(comment, commentSeq){\r\n");
      out.write("\t\t\t\tif(this.buttonFlag == false){\r\n");
      out.write("\t\t\t\t\tthis.buttonFlag = true;\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").val(comment.replace(/(<br>|<br\\/>|<br \\/>)/g, '\\r\\n'));\r\n");
      out.write("\t\t\t\t\tboardView.commentSeq = commentSeq;\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tthis.buttonFlag = false;\r\n");
      out.write("\t\t\t\t\t$(\"#boardComment\").val('');\r\n");
      out.write("\t\t\t\t\tboardView.commentSeq = '';\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(147,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(149,11) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.seq}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(157,13) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f3 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f3.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(158,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userNm}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f3 = _jspx_th_c_005fout_005f3.doStartTag();
    if (_jspx_th_c_005fout_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f4 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f4.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(159,25) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f4.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.userGroupNm}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f4 = _jspx_th_c_005fout_005f4.doStartTag();
    if (_jspx_th_c_005fout_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f5 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f5.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f5.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(162,20) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f5.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${projectView.projectStatCd}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f5 = _jspx_th_c_005fout_005f5.doStartTag();
    if (_jspx_th_c_005fout_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f6 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f6.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f6.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(175,19) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f6.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.seq}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f6 = _jspx_th_c_005fout_005f6.doStartTag();
    if (_jspx_th_c_005fout_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f6);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f7 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f7.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f7.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(213,27) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f7.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f7 = _jspx_th_c_005fout_005f7.doStartTag();
    if (_jspx_th_c_005fout_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f7);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f8(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f8 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f8.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f8.setParent(null);
    // /WEB-INF/views/qa/board/boardForm.jsp(301,26) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f8.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.seq}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f8 = _jspx_th_c_005fout_005f8.doStartTag();
    if (_jspx_th_c_005fout_005f8.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f8);
    return false;
  }
}
