/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-06-29 07:50:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.stats;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/nextlab.tld", Long.valueOf(1524211545637L));
    _jspx_dependants.put("jar:file:/D:/cvcbank/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mngbot/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1524211722455L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"sub_layout\">\r\n");
      out.write("\t\t<p class=\"cate_tit\"  v-show=\"reportFavList.length>0\">Favorite Reports</p>\r\n");
      out.write("\t\t<div class=\"sel_rpt_wrap\" v-show=\"reportFavList.length>0\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li class=\"ico_rpt\" v-for=\"list in reportFavList\" :class=\"{'fav':list.favorite!=0}\">\r\n");
      out.write("\t\t\t\t\t<button @click=\"openReportPop(list.reportUrl)\" v-bind:style=\"{background:list.color}\"><span>{{list.reportCd}}</span></button>\r\n");
      out.write("\t\t\t\t\t<span class=\"ico_fav\" @click=\"saveFav(event, list.reportId)\"></span>\r\n");
      out.write("\t\t\t\t\t<p class=\"name\">{{list.reportNm}}</p>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<p class=\"cate_tit\">리포트 검색</p>\r\n");
      out.write("\t\t<div class=\"rpt_sch_area\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"full\" @keypress=\"javascript:if(event.keyCode == 13) {getSerchList();}\" v-model=\"criteria.reportNm\" />\r\n");
      out.write("\t\t\t<button class=\"g_btn01\" @click=\"getSerchList()\"><span class=\"ico_sch\">검색</span></button>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"tb_desc\">\r\n");
      out.write("\t\t\t<p>조회결과 : {{reportList.length | number(0)}}건</p>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"report_list\">\r\n");
      out.write("\t\t\t<ul>\r\n");
      out.write("\t\t\t\t<li v-for=\"list in pagingList\">\r\n");
      out.write("\t\t\t\t\t<div class=\"ico_rpt\" :class=\"{'fav':list.favorite!=0}\">\r\n");
      out.write("\t\t\t\t\t\t<button @click=\"openReportPop(list.reportUrl)\" v-bind:style=\"{background:list.color}\">{{list.reportCd}}</button>\r\n");
      out.write("\t\t\t\t\t\t<span class=\"ico_fav\" @click=\"saveFav(event, list.reportId)\"></span>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"txt_area\">\r\n");
      out.write("\t\t\t\t\t\t<p class=\"tit\">\r\n");
      out.write("\t\t\t\t\t\t\t<a @click=\"openReportPop(list.reportUrl)\" >{{list.reportNm}}</a>\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"desc\">{{list.bigo}}</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"btn_list\">\r\n");
      out.write("\t\t\t\t\t\t<button class=\"g_btn01\" v-if=\"userAuthId =='AU006'\" @click=\"editReport(list.reportId)\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t<button class=\"g_btn02\" v-if=\"userAuthId =='AU006'\" @click=\"delReport(list.reportNm, list.reportId, list.favorite)\">삭제</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<div class=\"data_none\" v-if=\"pagingList.length == 0\">\r\n");
      out.write("\t\t\t\t\t<p>리포트 검색 결과가 없습니다.</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<paginator ref=\"paginator\" :go-fn=\"getPagingList\" :init-rows=\"5\"></paginator>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"top_fixed_btns\">\r\n");
      out.write("\t\t\t<div class=\"btn_link_all\" v-for=\"m in getReportMenuList\">\r\n");
      out.write("\t\t\t\t<button v-if=\"m.pageType == 'C103'\" @click=\"goModalView(m.menuUrl)\"><img :src=\"m.btnImg\" :alt=\"m.menuNm\"></button>\r\n");
      out.write("\t\t\t\t<button v-else :href=\"m.menuUrl\" @click=\"goReportSetting(reportUrl)\"><img :alt=\"m.menuNm\" :src=\"m.btnImg\"></button>\r\n");
      out.write("\t\t\t\t<span class=\"tooltip\">{{m.menuNm}}</span>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var list = new Vue({\r\n");
      out.write("\tel: '.content'\r\n");
      out.write("\t, data: {\r\n");
      out.write("\t\treportList: []\r\n");
      out.write("\t\t, pagingList: []\r\n");
      out.write("\t\t, criteria: {\r\n");
      out.write("\t\t\treportNm:\"\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t,reportFavList: []\r\n");
      out.write("\t\t,userAuthId : \"\"\r\n");
      out.write("\t\t,reportMenuList: []\r\n");
      out.write("\t\t,reportMenu:['000301', '000302']\r\n");
      out.write("\t\t,reportFavName: \"\"\r\n");
      out.write("\t\t,reportUrl: '");
      if (_jspx_meth_nl_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t}\r\n");
      out.write("\t, mounted: function() {\r\n");
      out.write("\t\t// nextTick은 모든 el 로드 후 동작\r\n");
      out.write("\t\tthis.$nextTick(function() {\r\n");
      out.write("\t\t\tthis.reportMenuList = JSON.parse(decodeURIComponent('");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("').replace(/\\+/g, \" \"));\r\n");
      out.write("\t\t\tthis.getList();\r\n");
      out.write("\t\t\tthis.getFavList();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t, computed: {\r\n");
      out.write("\t\tgetFirstPage: function(){\r\n");
      out.write("\t\t\treturn this.$refs.paginator.pageNumDesc;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, getReportMenuList:  function() {\r\n");
      out.write("\t\t\tvar reportMenu = this.reportMenu;\r\n");
      out.write("\t\t\treturn this.reportMenuList.filter(function(menuList) {\r\n");
      out.write("\t\t\t\tvar chk = false;\r\n");
      out.write("\t\t\t\treportMenu.forEach(function(m){\r\n");
      out.write("\t\t\t\t\tif(menuList.menuId === m){\r\n");
      out.write("\t\t\t\t\t\tchk = true;\r\n");
      out.write("\t\t\t\t\t\tmenuList.btnImg = \"/images/stats/btn_\" + menuList.menuId + \".png\";\r\n");
      out.write("\t\t\t\t\t\treturn;\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\treturn chk;\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t, methods: {\r\n");
      out.write("\t\tgetList: function() {\r\n");
      out.write("\t\t\t$.post('/stats/report/getReportList',list.criteria , function(data){\r\n");
      out.write("\t\t\t\tlist.reportList = data.reportList;\r\n");
      out.write("\t\t\t\tlist.userAuthId = data.userAuthId;\r\n");
      out.write("\t\t\t\tlist.getPagingList();\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, getSerchList: function(){\r\n");
      out.write("\t\t\t$.post('/stats/report/getReportList',list.criteria , function(data){\r\n");
      out.write("\t\t\t\tlist.reportList = data.reportList\r\n");
      out.write("\t\t\t\tlist.getPagingList();\r\n");
      out.write("\t\t\t\tlist.goPage(1)\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, getFavList: function() {\r\n");
      out.write("\t\t\t$.post('/stats/report/getReportFavList', function(data){\r\n");
      out.write("\t\t\t\tlist.reportFavList = data.reportFavList\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, getPagingList: function () {\r\n");
      out.write("\t\t\tthis.pagingList = this.$refs.paginator.pagingList(this.reportList);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, goPage: function(page){\r\n");
      out.write("\t\t\tthis.$refs.paginator.goPage(page);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t,delReport: function(reportNm, reportId, favorite) {\r\n");
      out.write("\t\t\tvar cmsg = reportNm+\"을 삭제하시겠습니까?\";\r\n");
      out.write("\t\t\tvar paramReportId = \"");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("\";\r\n");
      out.write("\t\t\tif (confirm(cmsg)){\r\n");
      out.write("\t\t\t\t$.post('/stats/report/delReportPrc',{reportId:reportId, favorite:favorite} , function(data){\r\n");
      out.write("\t\t\t\t\tif(data.del){\r\n");
      out.write("\t\t\t\t\t\talert(\"삭제되었습니다.\");\r\n");
      out.write("\t\t\t\t\t\tlist.getList();\r\n");
      out.write("\t\t\t\t\t\tlist.getFavList();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t,saveFav: function(event, reportId) {\r\n");
      out.write("\t\t\tvar gubun = '';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif ((event.target.parentNode.className) == 'ico_rpt') gubun = 'reg';\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$.post('/stats/report/saveFavoritesReportPrc', {reportId:reportId, gubun:gubun}, function(data) {\r\n");
      out.write("\t\t\t\tif(data.save){\r\n");
      out.write("\t\t\t\t\tlist.getList();\r\n");
      out.write("\t\t\t\t\tlist.getFavList();\r\n");
      out.write("\t\t\t\t} else{\r\n");
      out.write("\t\t\t\t\talert(\"저장 실패하였습니다.\")\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t})\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, goModalView: function(url) {\r\n");
      out.write("\t\t\tif (url) showPopupLayer(url);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, goReportSetting: function(url){\r\n");
      out.write("\t\t\tif (url) openReportPop(url);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, editReport: function(id){\r\n");
      out.write("\t\t\tlocation.href = \"#\";\r\n");
      out.write("\t\t\tshowPopupLayer('/stats/report/reportMngForm?reportId=' + id); \r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_nl_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f0 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f0.setParent(null);
    // /WEB-INF/views/stats/main.jsp(75,15) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f0.setKey("report.url");
    int _jspx_eval_nl_005fproperty_005f0 = _jspx_th_nl_005fproperty_005f0.doStartTag();
    if (_jspx_th_nl_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/stats/main.jsp(80,56) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${reportMenuList}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/stats/main.jsp(133,24) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.reportId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }
}
