/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-08-31 05:14:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.qa.flaw;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class flawList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/nextlab.tld", Long.valueOf(1524211545637L));
    _jspx_dependants.put("jar:file:/D:/cvcbank/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mngbot/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1524211722455L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fnl_005fradiobuttons_0026_005fv_002dmodel_005fcodeType_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fnl_005fradiobuttons_0026_005fv_002dmodel_005fcodeType_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fnl_005fradiobuttons_0026_005fv_002dmodel_005fcodeType_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("\t<div class=\"sub_layout has_snb\">\r\n");
      out.write("\t\t<div class=\"cont_wrap\">\r\n");
      out.write("\t\t\t<div class=\"sort_area\">\r\n");
      out.write("\t\t\t\t<div class=\"sel_item full\" style=\"left:-18px;right:18px\">\r\n");
      out.write("\t\t\t\t\t<span class=\"sort_tit\">조회구분</span>\r\n");
      out.write("\t\t\t\t\t");
      if (_jspx_meth_nl_005fradiobuttons_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<button class=\"g_btn01\" @click=\"getList\">조회</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"tb_desc\">\r\n");
      out.write("\t\t\t\t<p>조회결과 : {{ flawList.length | number(0) }}건</p>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"g_table\">\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<caption>중요도, 진행사황, 이슈제목 등으로 구성된 표입니다.</caption>\r\n");
      out.write("\t\t\t\t\t<colgroup>\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:5%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:5%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:8%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:11%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:15%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:14%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:14%;\">\r\n");
      out.write("\t\t\t\t\t\t<col style=\"width:10%;\">\r\n");
      out.write("\t\t\t\t\t</colgroup>\r\n");
      out.write("\t\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th>No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>차수</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>측정장비</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>TC No.</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Test Case</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>측정모델</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>리모컨</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Jira Link</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>Desc</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th>결함정보 입력</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t\t<tr v-for=\"(list, idx) in pagingList\">\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ getFirstPage - idx }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.chasu }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.botNm }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.tcId }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.tcNm }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.modelNm }}({{ list.modelVer }})</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.remoconNm }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.jiraLink }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>{{ list.flawDesc }}</td>\r\n");
      out.write("\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"smbtn_default\" v-if=\"(list.jiraLink != '' && list.jiraLink != null) || (list.flawDesc != '' && list.flawDesc != null)\" @click=\"goFlawForm(list.seq)\">수정</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button class=\"smbtn_default\" v-else @click=\"goFlawForm(list.seq)\">입력</button>\r\n");
      out.write("\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t<tr v-if=\"pagingList.length==0\">\r\n");
      out.write("\t\t\t\t\t\t\t<td colspan=\"9\">검색된 이슈가 없습니다.</td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<paginator ref=\"paginator\" :go-fn=\"getPagingList\"></paginator>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\tvar list = new Vue({\r\n");
      out.write("\t\tel: '.sub_layout'\r\n");
      out.write("\t\t, data: {\r\n");
      out.write("\t\t\tflawList: []\r\n");
      out.write("\t\t\t, pagingList: []\r\n");
      out.write("\t\t\t, criteria: {\r\n");
      out.write("\t\t\t\tpid: '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t\t, jiraLinkCd: 'D601'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, beforeMount: function() {\r\n");
      out.write("\t\t\tthis.$nextTick(function() {\r\n");
      out.write("\t\t\t\tthis.getList();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, mounted: function() {\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, computed: {\r\n");
      out.write("\t\t\tgetFirstPage: function(){\r\n");
      out.write("\t\t\t\treturn this.$refs.paginator.pageNumDesc;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, methods: {\r\n");
      out.write("\t\t\tgetList: function() {\r\n");
      out.write("\t\t\t\tvar param = this.criteria;\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\ttype: \"post\"\r\n");
      out.write("\t\t\t\t\t, url : \"/qa/flaw/getFlawList\"\r\n");
      out.write("\t\t\t\t\t, contentType: \"application/json\"\r\n");
      out.write("\t\t\t\t\t, data : JSON.stringify(param)\r\n");
      out.write("\t\t\t\t\t, success: function(data) {\r\n");
      out.write("\t\t\t\t\t\tlist.flawList = data.flawList;\r\n");
      out.write("\t\t\t\t\t\tlist.getPagingList();\r\n");
      out.write("\t\t\t\t\t\tlist.goPage(1);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t, error: function(xhr, status, error) {\r\n");
      out.write("\t\t\t\t\t\talert($(xhr.responseText).text());\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, getPagingList: function(page) {\r\n");
      out.write("\t\t\t\tthis.pagingList = this.$refs.paginator.pagingList(this.flawList);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, goPage: function(page) {\r\n");
      out.write("\t\t\t\tthis.$refs.paginator.goPage(page);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t, goFlawForm: function(seq) {\r\n");
      out.write("\t\t\t\tvar url = \"/qa/flaw/flawForm?seq=\" + seq;\r\n");
      out.write("\t\t\t\tgoShowPopupLayer(url);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_nl_005fradiobuttons_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:radiobuttons
    kr.co.nextlab.tag.CustomRadioButtonsTag _jspx_th_nl_005fradiobuttons_005f0 = (kr.co.nextlab.tag.CustomRadioButtonsTag) _005fjspx_005ftagPool_005fnl_005fradiobuttons_0026_005fv_002dmodel_005fcodeType_005fnobody.get(kr.co.nextlab.tag.CustomRadioButtonsTag.class);
    _jspx_th_nl_005fradiobuttons_005f0.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fradiobuttons_005f0.setParent(null);
    // /WEB-INF/views/qa/flaw/flawList.jsp(10,5) name = codeType type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fradiobuttons_005f0.setCodeType("D600");
    // /WEB-INF/views/qa/flaw/flawList.jsp(10,5) null
    _jspx_th_nl_005fradiobuttons_005f0.setDynamicAttribute(null, "v-model", "criteria.jiraLinkCd");
    int[] _jspx_push_body_count_nl_005fradiobuttons_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_nl_005fradiobuttons_005f0 = _jspx_th_nl_005fradiobuttons_005f0.doStartTag();
      if (_jspx_th_nl_005fradiobuttons_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_nl_005fradiobuttons_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_nl_005fradiobuttons_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_nl_005fradiobuttons_005f0.doFinally();
      _005fjspx_005ftagPool_005fnl_005fradiobuttons_0026_005fv_002dmodel_005fcodeType_005fnobody.reuse(_jspx_th_nl_005fradiobuttons_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/qa/flaw/flawList.jsp(79,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pid}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
