/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-09-27 02:10:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.bot;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/nextlab.tld", Long.valueOf(1524211545637L));
    _jspx_dependants.put("jar:file:/D:/cvcbank/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mngbot/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1524211722455L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<p class=\"com_logo\"><img src=\"");
      if (_jspx_meth_nl_005fproperty_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"");
      if (_jspx_meth_nl_005fproperty_005f1(_jspx_page_context))
        return;
      out.write("\"></p>\r\n");
      out.write("<div id=\"login\" class=\"login_wrap\">\r\n");
      out.write("\t<div class=\"login_box\">\r\n");
      out.write("\t\t<h1 class=\"syt_name\">");
      if (_jspx_meth_nl_005fproperty_005f2(_jspx_page_context))
        return;
      out.write("</h1>\r\n");
      out.write("\t\t<div class=\"login_area\">\r\n");
      out.write("\t\t\t<input type=\"text\" class=\"full\" placeholder=\"Login ID\" id=\"id\" v-model.trim=\"id\" @keypress.enter=\"login\">\r\n");
      out.write("\t\t\t<input type=\"password\" class=\"full\" placeholder=\"Password\" id=\"pwd\" v-model=\"pwd\" @keypress.enter=\"login\">\r\n");
      out.write("\t\t\t<input type=\"checkbox\" id=\"saveIdYn\" v-model=\"saveIdYn\"><label for=\"saveIdYn\">로그인아이디 기억하기</label>\r\n");
      out.write("\t\t\t<div class=\"btn_wrap\">\r\n");
      out.write("\t\t\t\t<button class=\"btn_login\" @click=\"login\">LOGIN</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"login_link\">\r\n");
      out.write("\t\t\t\t<a href=\"#\" @click=\"showPopupLayer('/bot/user/joinForm'); return false;\">계정 신청하기</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" @click=\"showPopupLayer('/bot/user/tempPwdForm'); return false;\">비밀번호 찾기</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\r\n");
      out.write("\t\tvar message = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\tif (message != \"\") {\r\n");
      out.write("\t\t\talert(message);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\tvar login = new Vue({\r\n");
      out.write("\t\tel: \"#login\"\r\n");
      out.write("\t\t, data: {\r\n");
      out.write("\t\t\tid: '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("'\r\n");
      out.write("\t\t\t, pwd: ''\r\n");
      out.write("\t\t\t, saveIdYn: false\r\n");
      out.write("\t\t\t, nextUrl: decodeURIComponent('");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write("')\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, mounted: function() {\r\n");
      out.write("\t\t\tthis.$nextTick(function() {\r\n");
      out.write("\t\t\t\tif (this.id!=\"\")\r\n");
      out.write("\t\t\t\t\tthis.saveIdYn = true;\r\n");
      out.write("\t\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tvar currentUrl = location.href;\r\n");
      out.write("\t\t\tvar siteUrl = '");
      if (_jspx_meth_nl_005fproperty_005f3(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\tvar siteIp = '");
      if (_jspx_meth_nl_005fproperty_005f4(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\tvar sitePort = '");
      if (_jspx_meth_nl_005fproperty_005f5(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("\t\t\tif (currentUrl.indexOf(siteIp) >= 0) {\r\n");
      out.write("\t\t\t\tlocation.href = siteUrl + ':' + sitePort;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t, methods: {\r\n");
      out.write("\t\t\tlogin: function() {\r\n");
      out.write("\t\t\t\tif (this.id==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif (this.pwd==\"\") {\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t\t$(\"#pwd\").focus();\r\n");
      out.write("\t\t\t\t\treturn;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t$.post(\"/bot/loginPrc\", this.$data, function(data) {\r\n");
      out.write("\t\t\t\t\tif (data.isLogin)\r\n");
      out.write("\t\t\t\t\t\tlocation.href = data.nextUrl;\r\n");
      out.write("\t\t\t\t\telse \r\n");
      out.write("\t\t\t\t\t\talert(data.message);\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_nl_005fproperty_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f0 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f0.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f0.setParent(null);
    // /WEB-INF/views/bot/login.jsp(4,30) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f0.setKey("site.company.logo");
    int _jspx_eval_nl_005fproperty_005f0 = _jspx_th_nl_005fproperty_005f0.doStartTag();
    if (_jspx_th_nl_005fproperty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f0);
    return false;
  }

  private boolean _jspx_meth_nl_005fproperty_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f1 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f1.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f1.setParent(null);
    // /WEB-INF/views/bot/login.jsp(4,76) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f1.setKey("site.company.name");
    int _jspx_eval_nl_005fproperty_005f1 = _jspx_th_nl_005fproperty_005f1.doStartTag();
    if (_jspx_th_nl_005fproperty_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f1);
    return false;
  }

  private boolean _jspx_meth_nl_005fproperty_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f2 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f2.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f2.setParent(null);
    // /WEB-INF/views/bot/login.jsp(7,23) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f2.setKey("site.bot.name");
    int _jspx_eval_nl_005fproperty_005f2 = _jspx_th_nl_005fproperty_005f2.doStartTag();
    if (_jspx_th_nl_005fproperty_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent(null);
    // /WEB-INF/views/bot/login.jsp(27,17) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f1.setParent(null);
    // /WEB-INF/views/bot/login.jsp(36,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${saveId}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
    if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f2.setParent(null);
    // /WEB-INF/views/bot/login.jsp(39,34) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextUrl}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
    if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
    return false;
  }

  private boolean _jspx_meth_nl_005fproperty_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f3 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f3.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f3.setParent(null);
    // /WEB-INF/views/bot/login.jsp(49,18) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f3.setKey("site.url");
    int _jspx_eval_nl_005fproperty_005f3 = _jspx_th_nl_005fproperty_005f3.doStartTag();
    if (_jspx_th_nl_005fproperty_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f3);
    return false;
  }

  private boolean _jspx_meth_nl_005fproperty_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f4 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f4.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f4.setParent(null);
    // /WEB-INF/views/bot/login.jsp(50,17) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f4.setKey("site.ip");
    int _jspx_eval_nl_005fproperty_005f4 = _jspx_th_nl_005fproperty_005f4.doStartTag();
    if (_jspx_th_nl_005fproperty_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f4);
    return false;
  }

  private boolean _jspx_meth_nl_005fproperty_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  nl:property
    kr.co.nextlab.tag.PropertyTag _jspx_th_nl_005fproperty_005f5 = (kr.co.nextlab.tag.PropertyTag) _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.get(kr.co.nextlab.tag.PropertyTag.class);
    _jspx_th_nl_005fproperty_005f5.setPageContext(_jspx_page_context);
    _jspx_th_nl_005fproperty_005f5.setParent(null);
    // /WEB-INF/views/bot/login.jsp(51,19) name = key type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_nl_005fproperty_005f5.setKey("site.port");
    int _jspx_eval_nl_005fproperty_005f5 = _jspx_th_nl_005fproperty_005f5.doStartTag();
    if (_jspx_th_nl_005fproperty_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005fnl_005fproperty_0026_005fkey_005fnobody.reuse(_jspx_th_nl_005fproperty_005f5);
    return false;
  }
}
